index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }

news:
    path: /news
    defaults: { _controller: 'App\Controller\NewsController:indexAction' }

guestbook:
    path: /guestbook/{page}
    controller: App\Controller\GuestbookController:indexAction
    defaults:
            page: 1
    requirements:
            page: '\d+'