home:
    path: /
    controller: App\Controller\HomeController:indexAction



article_home:
    path: /article/{page}
    controller: App\Controller\ArticleController:indexAction
    defaults:
            page: 1
    requirements:
            page: '\d+'

article_view:
    path: /article/view/{id}
    controller: App\Controller\ArticleController:viewAction
    requirements:
            page: '\d+'
article_add:
    path: /article/add
    controller: App\Controller\ArticleController:addAction

article_edit:
    path: /article/edit/{id}
    controller: App\Controller\ArticleController:editAction
    requirements:
                page: '\d+'

article_delete:
    path: /article/delete/{id}
    controller: App\Controller\ArticleController:deleteAction
    requirements:
                page: '\d+'

article_archive:
    path: /article/archive
    controller: App\Controller\ArticleController:archiveAction

guestbook:
    path: /guestbook/{page}
    controller: App\Controller\GuestbookController:indexAction
    defaults:
            page: 1
    requirements:
            page: '\d+'


gallery_home:
    path: /gallery/{page}
    controller: App\Controller\GalleryController:indexAction
    defaults:
            page: 1
    requirements:
            page: '\d+'

gallery_view:
    path: /gallery/view/{id}
    controller: App\Controller\GalleryController:viewAction
    requirements:
            page: '\d+'
gallery_add:
    path: /gallery/add
    controller: App\Controller\GalleryController:addAction

gallery_edit:
    path: /gallery/edit/{id}
    controller: App\Controller\GalleryController:editAction
    requirements:
                page: '\d+'

gallery_delete:
    path: /gallery/delete/{id}
    controller: App\Controller\GalleryController:deleteAction
    requirements:
                page: '\d+'

kms_froala_editor:
  resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
  prefix:   /froalaeditor

app_paramconverter:
    path: /test/{json}
    defaults:
      _controller: "App:article:ParamConverter"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"