index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }


post_home:
    path: /post
    controller: App\Controller\PostController:indexAction

post_view:
    path: /post/{id}
    controller: App\Controller\PostController:viewAction
    requirements:
            page: '\d+'
post_add:
    path: /post/add
    controller: App\Controller\PostController:addAction

post_delete:
    path: /post/delete
    controller: App\Controller\PostController:deleteAction

guestbook:
    path: /guestbook/{page}
    controller: App\Controller\GuestbookController:indexAction
    defaults:
            page: 1
    requirements:
            page: '\d+'