index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }

news:
    path: /news
    defaults: { _controller: 'App\Controller\NewsController:indexAction' }

guestbook:
    path: /guestbook
    defaults: { _controller: 'App\Controller\GuestbookController:indexAction' }